name: Supabase Keep-Alive

on:
  schedule:
    # Runs automatically at 00:00 every 3 days
    - cron: "0 0 */3 * *"
  workflow_dispatch:
    # Allows you to trigger it manually from the Actions tab if needed

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        run: |
          curl -X GET "https://fuhdialwabzedinesxye.supabase.co/rest/v1/halaqahs?limit=1" \
          -H "apikey: sb_publishable_KW6_cE5LFjk7g4BAKGhupA_tFzO8DxD" \
          -H "Authorization: Bearer sb_publishable_KW6_cE5LFjk7g4BAKGhupA_tFzO8DxD"
          echo "Ping complete!"